### ISSUE TITLE
Sound / Vibrations / HeartRate

### ISSUE THREAD

**Issue by MrNickH** [AsteroidOS/meta-sturgeon-hybris#4]
Hello Kind Developer

I am in owership of a sturgeon based device, and just wondering if you have any idea how to help me?
I have flashed 1.1 nightly to my devices (from the asteroid OS page) and seem to have no sound from any apps such as alarm countdown timer etc,

Heart Rate monitor seems always to report 0, and there are no vibrations at any time except when enabling and disabling virations

Not sure if this is an asteroid OS or  sturgeon issue, but any help would be appriciated.
Also the battery reports undefined%.

Thankyou for your time, and i'd love to learn how to develop asteroid as well as for this device.
(I can do web software, so not totally in the dark!)

**Comment by MagneFire** [comment]
Hi MrNickH,

Good to see that you have got AsteroidOS to work on your Huawei Watch!

You are correct when it comes to sound. None of the apps and system components of AsteroidOS currently do anything with the sound. The same is true when it comes to the microphone. This is something that may be worked on in the future.

With the hear rate monitor, is there a green light coming from the hear rate sensor? Because the hear rate monitor will show 0 until it has read something. For now it only seems to be able to start one reading(i.e. once the green light goes off it will no longer be able to start another reading.).
For debugging this, can you provide a `journalctl --no-pager` log?

Just to confirm, you are not getting vibrations when there are incoming notifications or when the phone connects to the watch?

**Comment by MrNickH** [comment]
Hi - thanks for your quick reply!

To confirm - it DOES vibrate (on connection/notification), just not say when you might expect (like on timer countdowns/alarms/etc) Guessing this is asteroid OS too?

Sorry to be a pain Heart rate does work, wasnt patient enough obviously!

Battery undefined% could be a killer for me though.

/sys/class/power_supply/battery does reveal battery percentage in one of its files though from my initial digging (not sure which one) 
Any idea on this?

Eager to learn now to contribute those as Quality of life things, would make it a full time smart wear for me.

WearOS is a nono as no google on my devices.

Cheers

**Comment by MrNickH** [comment]
God sake sorry

https://github.com/AsteroidOS/asteroid/issues/94

Thanks for your hard work!
